x-config:
  - &NODE_BUILDER "node/builder:0.0.1"
  - &CONTAINER_NAME "angular-container"
  - &BUILDER_CONTAINER_NAME "node-builder"
version: '3.7'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: *NODE_BUILDER
    container_name: *CONTAINER_NAME
    ports:
      - '4200:4200'
    volumes:
      - ./src:/usr/src/app/src
      - usr/src/app/node_modules
    command: ng serve --host 0.0.0.0 --poll 500
